name: dedes_run
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  hive: 2.2.3
  hive_flutter: 1.1.0
  flame: 1.13.1
  flame_audio: 2.1.6
  mockito: ^5.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: 2.0.1
  build_runner: ^2.4.7
  flutter_lints: 3.0.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/jgl-temple-v3/
    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/
    - assets/images/btn-nusanta/
    - assets/audio/
  fonts:
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
  uses-material-design: true
